### ISSUE TITLE
Updating Discogs model for newer genres

### ISSUE THREAD

**Issue by jasongrishkoff** [MTG/essentia-replicate-demos#12]
Apologies if this is naive (and I have a feeling it is), but the Discogs model is slightly outdated, and they've got many more genres on their platform today.

An example of a very popular new genre is Phonk: https://www.discogs.com/style/phonk

How would one go about updating this model to reflect some of these newer genres?

Jason

**Comment by dbogdanov** [comment]
Hi  @jasongrishkoff :) 
Closing this issue here. New model with a larger set of styles will be available soon.
