### ISSUE TITLE
demo notebook to process multiple audio files to extract features such as chords , beats etc

### ISSUE THREAD

**Issue by pmahan00** [MTG/essentia-replicate-demos#6]
Hi, is there a notebook or example by which essentia algorithims could be applied to multiple audio files and store the results into a csv file ? Features such as chords detection , rythm , similarity matrices etc ?

**Comment by palonso** [comment]
Hi @pmahan00,
we don't provide such a notebook but you can check our [python examples](https://essentia.upf.edu/python_examples.html) where we cover all the features you are interested in.
