### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by SergeyRyskin** [MTG/essentia-replicate-demos#7]
@dbogdanov Hello, I hope everything is going well. I'm using your ```effnet-discogs library``` via  **Replicate** and I ran into a problem right now. When I reported this issue to **Replicate** they directed me here :) so I want to output my audio file **(.wav or .mp3)** in ```JSON``` format. As ```https://replicate.com/mtg/effnet-discogs```  docs say use a output_format and give a type (**"JSON"** or _"Visualization"_). But I cant understand how to do it because doc is not detailed mutch. Can you give me a code example to output file **JSON** by using **Python**? ```Just want to change Default value from``` _Visualization_ **to JSON**  
_**best wishes**_

**Comment by palonso** [comment]
Hi @SergeyRyskin,
the JSON output was broken and it was just fixed here: b02baddbadc5dcd2c6f9badca6f375957b7a28bf . Thanks for reporting!

Can you try again and let us know if the problem is fixed?

**Comment by SergeyRyskin** [comment]
Hi @palonso,
I'm so glad you solved the code error. But can you provide an API code sample to verify?
```
import os
import replicate

#before running set the following environment variables as follows:
os.environ["REPLICATE_API_TOKEN"] = "api_token_here" #<---(API TOKEN)
output = replicate.run(
    "mtg/effnet-discogs:1532dd069fb4f0e27c6833e28815f6b8c194dfec76fd9cd73460540fd720ffe1",
    input={"audio": open("path/to/file", "rb")},
    output_format="JSON",  #---> using this part of code in the right place???
)
print(output)
```
The code part you saw above was written by reading and understanding from your documentation.

**Comment by palonso** [comment]
Almost!

It seems that `input` is a dict containing all the input parameters (just found it by trial and error!):

```python
import replicate
output = replicate.run(
    "mtg/effnet-discogs:1532dd069fb4f0e27c6833e28815f6b8c194dfec76fd9cd73460540fd720ffe1",
    input={"audio": open("/your/file.mp3", "rb"), "output_format": "JSON"},
)
print(output)
```

**Comment by SergeyRyskin** [comment]
Yes it worked now and everything seems fine :) Thank you for your help and feedback.
