### ISSUE TITLE
A discogs reference in music-arousal-valence/cog.yaml

### ISSUE THREAD

**Issue by shaolo1** [MTG/essentia-replicate-demos#9]
I'd fix it, but I don't know what it should be.

**Comment by dbogdanov** [comment]
Hi @shaolo1. In this demo we do not use [Discogs-EffNet](https://essentia.upf.edu/models.html#discogs-effnet) embeddings for arousal/valence estimation, as they showed slightly worse performance (see [Table 4](http://hdl.handle.net/10230/54181)).
